<img style="float:left" src="julialogo-smaller.png"/>

<br>
   * innovative open-source scientific programming language
   * **easy as Matlab, fast as Fortran, flexible as Python, deep as LISP**
   * leverages major C/Fortran science packages, e.g. LAPACK, MPI, FFTW... 
   * 5th language to run at 1 petaflops, after assembly, Fortran, C, C++ 
   * the future of scientific computing!
   
-- talk by John Gibson, Mathematics & Statistics, U New Hampshire

<br> 

# Background


  * started as MIT/UCSB applied math & computer science collaboration 2010 
    
  * founders Viral Shah, Jeff Bezanson, Stefan Karpinsky (now at Julia Computing LLC), Alan Edelman (MIT)
        
  * ~10-person core language team, ~600 contributors, ~1000 registered packages 
    
  * support from Intel, Microsoft, Wall St., Moore Foundation, NumFocus
   
  * julia-0.1 released 2012, julia-0.6 2017, julia-1.0 target 2018
  <br> <br> <br> <br> <br>

# Easy as Matlab


### Linear algebra 

In [2]:
A = randn(4,4)

4×4 Array{Float64,2}:
 -0.235443   -0.00462772  -0.84128  -0.297686
 -0.0325499  -0.373094     1.12805  -2.55145 
 -0.324119   -0.817885    -2.2023    1.46055 
  0.403108    1.02212     -0.29609   1.4256  

In [3]:
A[:,1]                # familiar colon syntax

4-element Array{Float64,1}:
 -0.235443 
 -0.0325499
 -0.324119 
  0.403108 

In [4]:
b = randn(4)          
x = A\b               # backslash operator
norm(A*x-b)

5.110814501696563e-16

In [5]:
U, Σ, V = svd(A);     # unicode variable name Σ
Σ

4-element Array{Float64,1}:
 3.92526 
 1.99094 
 0.677903
 0.167274

### Numerical integration of ODE

In [6]:
# define Lorenz dynamics ẋ = lorenz(t,x)
function lorenz(t, x)
    σ = 10
    β = 8/3
    ρ = 28
    [σ*(x[2]-x[1]); x[1]*(ρ-x[3]); x[1]*x[2] - β*x[3]]
end

# integrate ẋ = lorenz(t,x) numerically from t=0 to t=50
tspan = 0:0.02:50.0
x₀ = [1.0; 0.0; 0.0]
t,x = ode45(lorenz, x₀, tspan)
y = x
x = hcat(x...)';

# plot Lorenz attractor
plot(x[:,1], x[:,2], x[:,3], l=:path3d, xlab="x", ylab="y", zlab="z", label="")

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
<polyline clip-path="url(#clip1800)" style="stroke:#000000; stroke-width:1; stroke-opacity:1; fill:none" points="
 141.829,298.666 155.984,302.909 154.55,304.162 155.984,302.909 182.642,310.9 179.773,313.405 182.642,310.9 209.299,318.891 207.865,320.143 209.299,318.891 
 235.957,326.882 233.088,329.386 235.957,326.882 262.614,334.872 261.18,336.125 262.614,334.872 289.272,342.863 286.403,345.368 289.272,342.863 315.929,350.854 
 314.495,352.106 315.929,350.854 342.587,358.845 339.718,361.349 342.587,358.845 346.659,360.065 
 "/>
 
 
 
 
 
 
 
 
 x 
 
 
 y 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
<polyline clip-path="url(#clip1802)" style="stroke:#009af9; stroke-width:1; stroke-opacity:1; fill:none" points="
 189.219,163.692 195

### Going beyond Matlab, quick demo

In [7]:
⊕ = (x,y) -> 3x + 2y       # define ⊕ operator (unicode)

@show 5 ⊕ 1;   println()   # apply ⊕ to two Int64s

@show 2//5 ⊕ (3 - 7im);    # Rational{Int64} ⊕ Complex{Int64} produces Complex{Rational{Int64}

5 ⊕ 1 = 17

2 // 5 ⊕ (3 - 7im) = 36//5 - 14//1*im


<br> <br> <br> <br> <br>


# Julia: fast as Fortran

### Kuramoto-Sivashinsky equation

The Kuramoto-Sivashinsky (KS) equation is a nonlinear time-evolving partial differential equation (PDE) on a 1d spatial domain.

\begin{equation*}
u_t = - u_{xx} - u_{xxxx} - u u_x
\end{equation*}

where $x$ is space, $t$ is time, and subscripts indicate differentiation. We assume a spatial domain $x \in [0, L_x]$ with periodic boundary conditions and initial condition $u(x,0) = u_0(x)$. 

### KS-CNAB2 integration algorithm

Represent the linear terms as $Lu = (-D^2 -D^4)\, u$ and the nonlinear term as $N(u) = 1/2\, D \,u^2$ where $D = \partial/\partial x$.

\begin{equation*}
u_t = Lu + N(u)
\end{equation*}

Discretize time by letting $u^n(x) = u(x, n\Delta t)$ for some small $\Delta t$, and use Crank-Nicolson, Adams-Bashforth (CNAB2) timestepping. 

\begin{equation*}
\frac{u^{n+1} - u^n}{\Delta t} = L\left(\frac{u^{n+1} + u^n}{2} \right) + \frac{3}{2} N(u^n) - \frac{1}{2} N(u^{n-1})
\end{equation*}


Put the unknowns (future) $u^{n+1}$'s on the LHS and knowns (past) $u^{n}$ and past $u^{n+1}$ on the RHS.

\begin{equation*}
\left(I  - \frac{\Delta t}{2} L \right) u^{n+1} = \left(I  + \frac{\Delta t}{2}L \right) u^{n} + \frac{3 \Delta t}{2} N(u^n) - \frac{\Delta t}{2} N(u^{n-1})
\end{equation*}

Discretize space with a finite Fourier transform, so that $(I  \mp \Delta t/2 \, L)$ becomes diagonal matrices $A$ and $B$, and $N^n$ is the Fourier transform of $N(u^n)$.

\begin{equation*}
A \, u^{n+1} = B \, u^n + \frac{3 \Delta t}{2} N^n -  \frac{\Delta t}{2}N^{n-1}
\end{equation*}

This is an $Ax=b$ problem whose iteration approximates the time-evolution of the Kuramoto-Sivashinksy PDE. 

### Julia code for KS-CNAB2 algorithm

In [8]:
function ksintegrate(u₀, Lₓ, Δt, Nsteps, nsave);
    uⁿ = (1+0im)*u₀                      # force u to be complex
    Nₓ = length(uⁿ)                       # number of gridpoints
    kₓ = vcat(0:Nₓ/2-1, 0:0, -Nₓ/2+1:-1)  # integer wavenumbers: exp(2πikₓ x/L)
    α  = 2*pi*kₓ/Lₓ                       # real wavenumbers:    exp(iαx)
    D  = 1im*α                           # spectral D = d/dx operator 
    L  = α.^2 - α.^4                     # spectral L = -D^2 - D^4 operator
    G  = -0.5*D                          # spectral -1/2 D operator
    
    Nsave = div(Nsteps, nsave)+1         # number of saved u's, including t=0
    t = (0:Nsave)*(Δt*nsave)             # times of saved u's
    U = zeros(Nsave, Nₓ)                 # matrix of u(tᵢ, xⱼ) values
    U[1,:] = real(u₀)                    # assign initial condition to U
    s = 2                                # counter for saved data
    
    # construct diagonal matrices for LHS and RHS linear operators
    I   = ones(Nₓ)
    A⁻¹ = (I - Δt/2*L).^(-1)             
    B   = I + Δt/2*L
    
    # compute in-place FFTW plans
    FFT!  = plan_fft!(uⁿ,  flags=FFTW.ESTIMATE)
    IFFT! = plan_ifft!(uⁿ, flags=FFTW.ESTIMATE)

    # initialize nonlinear terms 
    Nuⁿ  = G.*fft(uⁿ.^2)      # set Nuⁿ = -1/2 d/dx (uⁿ)² = -u uₓ 
    Nuⁿ⁻¹ = copy(Nuⁿ)         # set Nuⁿ⁻¹ = Nuⁿ for first time step
    FFT!*uⁿ
    
    # timestepping loop
    for n = 1:Nsteps
        
        Nuⁿ⁻¹ .= Nuⁿ        # shift nonlinear term in time
        Nuⁿ  .= uⁿ         # store uⁿ in Nuⁿ in prep for collocation computation
        
        IFFT!*Nuⁿ          # transform to gridpt values of u
        Nuⁿ .= Nuⁿ.*Nuⁿ    # collocation calculation of u²
        FFT!*Nuⁿ           # transform u² back to spectral coeffs

        Nuⁿ .= G.*Nuⁿ      # compute  Nuⁿ = -1/2 d/dx u² = -u uₓ

        # Loop fusion! Julia unrolls this line into a single for-loop over vector elems,
        # avoiding the generation and allocation of temporary vectors you'd get in Matlab!
        uⁿ .= A⁻¹ .* (B .* uⁿ .+ 3Δt/2.*Nuⁿ .- Δt/2.*Nuⁿ⁻¹)
        
        if mod(n, nsave) == 0
            U[s,:] = real(ifft(uⁿ))  # save into return matrix U 
            s += 1            
        end
    end
   
    t,U
end

ksintegrate (generic function with 1 method)

### Execute Julia KS-CNAB2 code

In [9]:
# set discretization parameters
Lx = 64π
Nx = 1024
Δt = 1/16
nsave = 8
Nsteps = 3200

# set initial condition
x = Lx*(0:Nx-1)/Nx
u₀ = cos.(x) + 0.1*sin.(x/8) + 0.01*cos.(x/32);

# integrate PDE
t,U = ksintegrate(u₀, Lx, Δt, Nsteps, nsave) 

# plot results
heatmap(x,t, U, xlim=(x[1], x[end]), ylim=(t[1], t[end]), xlabel="x", ylabel="t", title="u(x,t)", fillcolor=:bluesreds)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 50 
 
 
 100 
 
 
 150 
 
 
 200 
 
 
 0 
 
 
 50 
 
 
 100 
 
 
 150 
 
 
 200 
 
 
 u(x,t) 
 
 
 x 
 
 
 t 
 
 
<image width="470" height="329" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAAdYAAAFJCAYAAAAmKgzMAAAgAElEQVR4nOy92Y5lSXYltmw40z13
9jE85si5Kiuriiw2u5s9SoKAbgjqF32TXvUN+gM9SIIgEOhuAQTZJEVWqYpF5pwxeLiHT3c8sw16
2GZ2jkdRT3otTzgyMiPi+r3HzPZee+21lwEAmOT4/dfvv37/9fuv33/9/uv3X///v9j//j/9j9bU
DcAYxGiE+PgQo6eP8fouxqsfKry7rLHbKHTKgnMgywSShCOKOIRkYAxgDAAYOAeEYIhijjTlmM0j
TGcS80WMcWbQXF5h/+XXaN5eor25hS4rsDhCenqCw//6X2PNl/h//naLH74rsFkrMAacnCY4Oklw
dJxgeRBhMoswmUpEEQMHYFQH07TQRYH6/ALN5RWq87f0M27vAMaQPjzD7Oc/wcG/+hP8za9K/Opv
6GdIybE8iHD2KMOTpxmePBthLraoXr5G9fI1ypevUb96g/Lla1itES8XGH/6ERb//I+x/Jd/gv/1
f7nE+esKda2RZQLLgxjPPhi59xpjMmbo7tZob+9QvXqN9uYWarODUQpykmP09AmSX/wz/OWfr/Cr
v9ng5fcldluF8Vji8DjGg7MUDx6lOHuY4sFZisO8RfX6HNXrN6hen6O5fAe13kJMxsg/eI75P/lD
lIsn+Ms/W+Gv/3KFujbIc4GT0wRPno3w/IMcHz7lKL9/ierNOdqrG6h9ATFKkZ6dYfzZx6hHR/i7
X+/w/bcFri4bCMkwnUU4Pknw4GGKzz6fQJYbVK/foD6/QHt1jW67A5cC8fER8o8+wPSLz/EP/1Dg
u68LvD2vwRkwnkocHiY4Pknw5HmG2UxC7QuYpgWMARgDkwJgDFZpmLpCt9nRc7u+QbfewHYKYjzG
6NkTzP/tv8Ff/Zc1fvOrLd68qlAWCnHMcfY4w8kJ7ZmDgxizhcTyIMZ4LKH2e3QrWo/m3RXKb75D
e7eCaVrIcY7s6ROc/od/j99+pfDLv1nj5Q8Vij297uOnGR6cpTh9kOLwOMZiEWE8kbBNDdN1sErB
Kg2rFHRZQVcVdFFC7XZQmy269QbNuyvoooLVGjxNEB8eYP5HP8fk8x/h/Ibjm68KvH1TYbtRMMYi
TQXGE4npTGI2j3B8mmAykchzgTjh4Jyh6yxWdy3Wqw53ty02a4WyUOg6iyTlmEwkDg5jHJ8mOHuU
of3+O9SXl+hWG0BryNkUo2dPcGmO8au/3eDrf9jj3WWDtjWYzSMcHMY4Ok5weBRjsYzc+4kQxxxx
Quc8Szm67RbVqzdoLq/QvLtCd7eCaRrEBwcYffQCsz/4Kb55ZfDrX27xyu3zbERnhs53jNOzFHku
kKQCUcQgJUMUcaCtobY7tLd3aK+u0Vxd07pVNeR0itHzJ5j+9HNc7DL85z+9weVFjaYxSDOBg4MY
Jw8SfPBRjsOjBPNlBN410HUD23WwAFgfxGCNhi5K6H2BbrVGc3NLn+nyHarX5zBNA5GmSB8+wOTH
n+LkP/x7fP/a4OV3BdZrBQDIxwKPHmc4dvuwvbpC/fYS+99+ierVG9Tnbyk2GYv46AAn//2/w9F/
+1/hP/3pDX7512u8fVvDaIuHjzKcPUrx4GGKw6ME44mElAxdZ1AWGvu9QrHXqEqNpjEAACGAKKK1
mUwkRrkIa7ZYRmivb1B88z2ay3dorm+g9wXAGOKDBRb//J9CHT7Cr3+5xTdfFbi9acAYo713EuPk
QYqTU9oLia2h9wV0XcO0HaxWgDaw1gLWwhoDGAOrDUzbwipF56TrYNoOpmmgNluofYFus4Xa7qCL
AtZYRIsZRs+fYfazn2D+x7/Ar365w1/9+QrrdQdYYJQLzJcRHj3KMF9SPshziTTjiGOOLBMwbQtT
11DuDHbrDerzC3R3K6jdHrbrwJMYo+fPMPrgOcaffoSXLxtcnNfYbjowxjCeCMwWEZbLGLN5hFR0
0E0LqzQAS/uGc8BYykNVA1UUULsdpMuGYC6wMUHBTUoW3qRWFqqzYBxIEtr0PqkCFBcBC2vpv4W2
MJr+21og/Abo19Z/w4JyMr1Bra37Boyx4Jxh8DcJCfhvxmC1htWGFq3tYOoGuqpgKgpspmnBkxg8
khBZBiNiFPsdmlrDWgIBccKRZdxtQAF1sXXBd4Xu9g7dZgsYAzkZI330EOPPPsH0ix/jy7/f4fam
gVIWWSYwX0RYHsaYzyOMcnpGjHHwNIGcjBEt5rDaANZC7UvYTqG9W2PSbPD8xQi3Ny32OwXVWXSd
QVVqFHuN0h+c2oDNIzApwYQA4xyMcXoY9GABa8EZwHj/v9z+hjH0bJmU4HEEniTgaQKhFHgUgwkO
GIMo4khSjjQTSFIOxhiEYH7pYLQFE5zeQ/i3ABOSXltKgHFoRT/PGgvDGe0F9w+9ltsc1tAhZAzM
cgSkxt3rus8L0Hqbuoba7cC7GtOpxGhEzxoAtLboWoOuM1CdgdIGRqPfh4yF58Y4B/wzBGBNv49k
xCEEAwNgDb0urQutTRd+bRFJCeaDCBQl1rqiwLzdUlLdbKF3e1hrIfIMIssQLRdITk+QPX4EnucQ
qxrLZQQGYDpTKAtNz89alCXtVy4Y2tag6yKMJwJZRp99OovAOHPHiABuVWoYY9E0BsVeY7dV2Kw6
TOczAjRlDbXfQ+32aN5d4ckfPcPtbYv1XYf9XqNbdahKjf1OIc0E0owToI45us5ACAZr7P3nyrnb
E7SO1rqA0zQwdY0kSRFFBAiMsVDKQinjvocxw8Ja2jPGAiK8tuj3vtsPtmvdua+RpDmEpP1jDKCV
W6/WrZmifZFEEkwpWKPBaGPCGg24JKC2FIjb61s07wgotNc3MG0LkaVIH5xi/NnHmP7sJ3j7Drh8
W6NuDNKUI88l5ssIp2cplgcR1HpNSaOsKNirDlZrwALgDCyOIEYj7HcK+51CUWjUFf3+/b1G+5qB
4iT9dTqbUcRgDJ0Bzun/cc4AFo4YjLEwxtKef2/vA3ROrdaQkoU9ROfCnWFDZ9+4+MwkB0S/5rAC
1low059tqzVM24VYbJrGfdOvdVnBNJS8RZaCJzFEmiI6WCA9O0W0nENb+nyTqQx7Jo45GIBOGToP
rUEXG8iIIYr85zEwShF4ajvYpqV/a015RErwNIOcTRDNZygri7LQaBsDa4EopgIxiQXimCOKGWzr
gukgqTLGYblx4IzyEmMMkoVDwQZBUtxDP4QgqWKNEwEpGQVvSwtmrfU/D4a5IO4W0xq4UMpCsA+R
zidc9x50228AYywlbos+ubqsSp/BwhgdkJBpWuiqhi4rqKJ0G7kBTxPwhJLbdtthv1OoK0J3UcSQ
pgKjXGI8lshHHOvVBt3dCt3dHbr1BroswZMEyfER8o9eYPqTH+O6SPH9txsUew0hgPGEDpNH9Gkq
wAWDZQw8SSDGBtFsBtsp2LaF6RQhtt0O9Zu3ePKTz/HuXYO7mxZFobFZd2gag7LSKEuNqjSoawMe
p+CRpCQmBKGlgLRpM3HeAx5r6VBo3Qcxn1RFmkCkKVVPUUSvZwEZc6QpBe0kFQGA0HrTOt/bJz6Q
iv7AGuvW3e1D7hKUNfcxFtz7s9aAWQrUjFmXW1mfuLmrZLWhA1mU6DZbTKZTB2IIAAwToFIUALTp
gR

### KS-CNAB2 benchmark: CPU time versus gridsize

Identical algorithm in six languages

<img style="float:left" src="ks_cpu_scaling.svg"/>

### KS-CNAB2 benchmark: CPU time versus lines of code 

<img style="float:left" src="ks_cpu_vs_lines.svg"/>


### General benchmarks, common code pattterns

<img style="float:left" src="benchmarks.svg"/>


# Julia: easy, dynamic, and fast. How? 


### Just-in-time compilation

Functions are compiled to machine code when first run. Subsequent runs are as fast as compiled C, C++, Fortran.

#### Logistic map example $f(x) = 4x(1-x)$.


In [10]:
f(x) = 4x*(1-x)     # define logistic map
@time f(0.3);       # run it once
@time f(0.3);       # run it again, faster by a factor of thousands

  0.003441 seconds (497 allocations: 29.339 KiB)
  0.000001 seconds (5 allocations: 176 bytes)


In [11]:
@time f(0.67)

  0.000003 seconds (5 allocations: 176 bytes)


0.8844

In [12]:
@code_llvm f(0.3)   # show f(x) in intermediate compiler language (LLVM)


define double @julia_f_65044(double) #0 !dbg !5 {
top:
  %1 = fmul double %0, 4.000000e+00
  %2 = fsub double 1.000000e+00, %0
  %3 = fmul double %1, %2
  ret double %3
}


In [13]:
@code_native f(0.3) # show f(x) in IA-64 assembly language

	.text
Filename: In[10]
	pushq	%rbp
	movq	%rsp, %rbp
	movabsq	$140559138773184, %rax  # imm = 0x7FD6798958C0
	movabsq	$140559138773192, %rcx  # imm = 0x7FD6798958C8
Source line: 1
	movsd	(%rcx), %xmm1           # xmm1 = mem[0],zero
	subsd	%xmm0, %xmm1
	mulsd	(%rax), %xmm0
	mulsd	%xmm1, %xmm0
	popq	%rbp
	retq
	nopw	(%rax,%rax)


#### Millionth iterate of logistic map, Julia

In [ ]:
# define function that, given function g(x), returns iterated function gᴺ(x)
function iterator(g, N)
    
    # construct gᴺ, the Nth iterate of g
    function gᴺ(x)
      for i ∈ 1:N             
        x = g(x)
      end        
      return x
    end    
    
    return gᴺ
end

# use iterator function to generate millionth iterate function for logistic map
fᴺ = iterator(f, 10^6);

@time x = fᴺ(0.67)
@time x = fᴺ(0.67);

#### Millionth iterate of logistic map, C++

In [ ]:
; cat fN.cpp

In [ ]:
; g++ -O3 -o fN fN.cpp -lm  

### Compare execution time of fN in Julia, C++, Matlab

#### Julia

In [ ]:
print("t=");                 # run the Julia fᴺ on x = 0.67
@time x = fᴺ(0.67);
@show x;

#### C++

In [ ]:
; fN 0.67 

Julia and C++ get the same result `x` in roughly same execution time `t`. Sometimes Julia is faster, sometimes C++.

#### Matlab
```
>> tic(); x=fN(0.67); t=toc();
>> t, x
t = 0.048889000000000
x = 0.101168853345475
```
Matlab gets the same result $x$, but about ten times slower than Julia or C++.

## Type inference

Julia reasons about types and infers types of variables from context, enabling compilation to hardware instructions. 

Language and type system carefully designed maximize effectiveness of just-in-time compilation. Matlab, Python syntax precludes this.



In [ ]:
# recall definition of f(x): no types are mentioned!
f(x) = 4x*(1-x)

In [ ]:
typeof(f)

In [ ]:
@code_llvm f(0.3)   # machine code for f applied to Float64 argument

In [ ]:
@code_llvm f(2)     # machine code for f applied to Int64 argument

In [ ]:
@code_llvm fᴺ(0.67) 

<br> <br> <br> <br>

# Julia: flexible as Python

### Comprehensive numeric type system

In [ ]:
# define a set of various numeric types
X = (1, 0.5f0, 0.5, 2//3, 2+3im, 2.1 + 4.3im, 2//3 + 4//5im, BigFloat(2//3), BigFloat(2//3) + BigFloat(4//5)*im);

# loop over elements of X, print type and compute value of logistic map f(x)
for x ∈ X
    println("typeof(x) = $(typeof(x)), f(x) = $(f(x))\n")
end

In [ ]:
# exact arithmetic: compute iterated logisitic map on Rational{BigInt}
fᴺ = iterator(f, 7)
@show fᴺ(big(2//3));

### Singular values of Hilbert matrix

The Hilbert matrix $A_{ij} = (i+j-1)^{-1}$ is notoriously ill-conditioned. 

In [ ]:
m = 8
A = [1//(i+j-1) for i=1:m, j=1:m]    # 8 x 8 Hilbert matrix of Rationals

In [ ]:
# 16 x 16 Hilbert is too ill-conditioned for 64-bit arithmetic 
m = 16
A = [1/(i+j-1) for i=1:m, j=1:m]    # 16 x 16 Hilbert matrix of Float64s
@show cond(A)
@show eps(Float64)

In [ ]:
# Make 32 x 32 Hilbert matrix of BigFloats and show a few elements

m = 32
A = [BigFloat(1//(i+j-1)) for i=1:m, j=1:m]; 
@show A[1,1]
@show A[2,1]
@show A[3,1]
;

In [ ]:
# Compute singular values of 32 x 32 Hilbert matrix in 256-bit arithmetic
σ = svdvals(A)

## User-defined type: Galois field GF(p)

Finite scalar field GF(p) is $\mathbb{Z}/p$, the integers modulo p, where p is prime. Example by Andreas Noack, Julia Computing.

In [14]:
# Define Galois fields GF(p), where p is the prime modulus, T is the integer type
immutable GF{p,T} <: Number where {p,T<:Integer}
    rep::T  # representative integer which holds the value of a GF(p) variable
    function GF{p,T}(x::Integer) where {p,T<:Integer}
        return new(mod(x, p))
    end
end
GF{p}(x::T) where {p,T<:Integer} = GF{p,T}(x)


# Define some basic methods for GF(p) that all Julia Numbers must have
import Base: convert, inv, one, promote_rule, show, zero

function call{p}(::Type{GF{p}}, x::Integer)
    if !isprime(p)
        throw(ArgumentError("p must be prime"))
    end
    return GF{p,typeof(x)}(mod(x, p))
end

convert{p,T}(::Type{GF{p,T}}, x::Integer) = GF{p}(x)
convert{p}(::Type{GF{p}}, x::Integer) = GF{p}(x)
convert{p,T}(::Type{GF{p,T}}, x::GF{p}) = GF{p,T}(x.rep)
promote_rule{p,T1,T2<:Integer}(::Type{GF{p,T1}}, ::Type{T2}) = GF{p,promote_type(T1,T2)}
show(io::IO, x::GF) = show(io, x.rep);


# Define arithmetic operations on GF(p)
import Base: +, -, *, /

for op in (:+, :-, :*)   # loop over ops, defining each in terms of integer ops mod p
    @eval begin
        ($op){p,T}(x::GF{p,T}, y::GF{p,T}) = GF{p,T}($(op)(x.rep, y.rep))
    end
end

# Define inverse and ÷. Requires more care than +, -, * because dividing by zero throws error
function inv{p,T}(x::GF{p,T})
    if x == zero(x)
        throw(DivideError())
    end
    r, u, v = gcdx(x.rep, p)
    GF{p,T}(u)
end
(/){p}(x::GF{p}, y::GF{p}) = x*inv(y);

In [15]:
# Create some GF(7) variables and do arithmetic

x = GF{7}(9)   # x =  9 mod 7 = 2
y = GF{7}(12)  # y = 12 mod 7 = 5
@show x
@show y
@show x + y     # 2 + 5 mod 7 = 0
@show x - y     # 2 - 5 mod 7 = 4
@show x * y     # 2 * 5 mod 7 = 3
@show x / y     # 2 ÷ 5 mod 7 = 6, because 2 = 6*5 mod 7
;

x = 2
y = 5
x + y = 0
x - y = 4
x * y = 3
x / y = 6


### Linear algebra over Galois field

In [16]:
srand(1234)
A = [GF{7}(rand(0:6)) for i = 1:4, j = 1:4] # matrix of random GF(7) elems

4×4 Array{GF{7,Int64},2}:
 3  5  3  3
 6  6  2  0
 2  2  6  4
 2  6  1  2

In [17]:
b = [GF{7}(rand(0:6)) for i = 1:4]          # random vector b for Ax=b problem

4-element Array{GF{7,Int64},1}:
 1
 4
 3
 0

In [18]:
x = A\b   # solve Ax=b over GF(p)!

4-element Array{GF{7,Int64},1}:
 5
 5
 0
 1

In [19]:
A*x - b   # check that x satisfies Ax=b

4-element Array{GF{7,Int64},1}:
 0
 0
 0
 0

**Whoa! Built-in backslash operator on matrix of GF(p) worked!** 

Julia generated and compiled a GF(p)-specific version of its generic LU decomp function. 

All it needs is definitions of $+, -, \times, \div$.

<br> <br> <br> <br>




# Julia: deep as Lisp

Julia is *homoiconic*: it can represent its own expressions as data structures and operate on them

### Expressions

In [ ]:
program = "for n ∈ 1:N begin println(n^2) end end"

In [ ]:
expression = parse(program)

In [ ]:
dump(expression)

In [ ]:
program

In [ ]:
N = 3; eval(expression)

In [ ]:
N = 5; eval(expression)

### Macros: code that transforms code

In [ ]:
# @show macro prints expression, an equals sign, then evaluates the expr and prints its value
@show 3*A[:,1] + 7*A[:,2];

In [ ]:
# @time macro inserts timing and memory profiling into expression, then evaluates, and prints
@time f(2//3)

In [ ]:
# @which macro determines which function is called, provides link to source code on GitHub
@which exp(π)

In [ ]:
@which exp(π*im)

In [ ]:
# run-time code generation and evaluation using @eval macro (example from Galois field GF(p))

for op in (:+, :-, :*)   # loop over ops, defining each in terms of integer ops mod p
    @eval begin
        ($op){p,T}(x::GF{p,T}, y::GF{p,T}) = GF{p,T}($(op)(x.rep, y.rep))
    end
end

Macros enable run-time code generation and transformation. Applications

  * generation and execution of boilerplate code
  * run-time generation and optimization of algorithms, e.g. FFTW, ATLAS
  * automatic diferentiation
  * symbolic mathematics

# Conclusions

Julia
  * easy as Matlab, fast as Fortran, flexible as Python, deep as Lisp
  * poised to take over scientific computing, from interactive exploration to HPC

Not covered
  * parallel programming: MPI and higher-level constructs
  * large-scale programming, development ecosystem, environments, debuggers, etc.
  * interfaces to major C/Fortran libraries, e.g. LAPACK, MPI, FFTW, PETSc, etc.   
  * rough edges: plotting, package loading times, syntax flux

Thanks
  * Julia team, Julia community
  * David Sanders, National University of Mexico City
  * Andreas Noack, Julia Computing 
  * Mahtab Lak, UNH Math Ph.D. student

  
Julia website: http://www.julialang.org, this talk: https://github.com/johnfgibson/whyjulia
<br> <br> <br>  <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br>

#### Preload and run some functions

In [1]:
using ODE, Plots, GenericSVD     # load some packages 
gr();                            # set plotting backend
t = linspace(0,4π)
x,y,z = cos.(t), sin.(t), t
plot(x, y, z, l=:path3d, xlab="x", ylab="y", zlab="z", label="")

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
<polyline clip-path="url(#clip0700)" style="stroke:#000000; stroke-width:1; stroke-opacity:1; fill:none" points="
 146.771,298.666 172.19,306.286 170.756,307.538 172.19,306.286 197.821,313.969 194.952,316.473 197.821,313.969 223.451,321.652 222.016,322.904 223.451,321.652 
 249.081,329.334 246.212,331.839 249.081,329.334 274.711,337.017 273.277,338.269 274.711,337.017 300.341,344.7 297.473,347.204 300.341,344.7 325.971,352.383 
 324.537,353.635 325.971,352.383 351.601,360.065 348.733,362.57 351.601,360.065 
 "/>
 
 
 
 
 
 
 
 
 
 
 x 
 
 
 y